Pull Request
vlad133L/weather-app pull request #1
Opened 2022-08-15 19:37 UTC by vlad133L

2022-08-17 07:14 UTC, AYakhimovich requested changes

2022-08-17 07:14 UTC, AYakhimovich commented on index.js
> +}
please create `cityEnum`:

```
const cityEnum = {
       MINSK: 'Minsk',
       LVIV: 'Lviv',
    .......
}
```

use enum in the `citiesCoords`

create file `constants.js` and put `enum` and `citiesCoords` there

2022-08-17 07:14 UTC, AYakhimovich commented on index.js
> +  const data = await weatherInfo.get(citiesCoords[selectedCity].latitude,citiesCoords[selectedCity].longitude);
put just selected city there, citiesCoords has to be used inside of the weatherInfo.get

2022-08-17 07:14 UTC, AYakhimovich commented on index.js
> +  const weatherInfo = new WeatherResource();
it has to be weatherResource because it is instance of WeatherResource

2022-08-17 07:14 UTC, AYakhimovich commented on index.js
> +  weatherService.showCountry(data.sys.country);
weatherInfo.get has to return already mapped data, i mean, instead of data.sys.country, you have to had country, you can create data mapper inside WeatherResource service

2022-08-17 07:14 UTC, AYakhimovich commented on services/weatherResource.js
> +		 const response = await fetch(`https://fcc-weather-api.glitch.me/api/current?lat=${latitude}&lon=${longitude}`);
put this part of url `https://fcc-weather-api.glitch.me` into the field in constructor, it can be called baseUrl for instance

2022-08-17 07:14 UTC, AYakhimovich commented on services/weatherResource.js
> + }
add new line

2022-08-17 07:14 UTC, AYakhimovich commented on services/weatherService.js
> +	  document.querySelector('.weather__info-temperature').textContent = `Temperature: ${temperature} °C`;
you can create method `changeTextContent` for example, and use it all over this service,

```
changeTextContent(selector, text) {
  document.querySelector(selector).textContent = text;
}

showTemperature(temperature) {
  const selector = '.weather__info-temperature';
  const textContent = `Temperature: ${temperature} °C`;
  
  this.changeTextContent(selector, textContent)
}

```

2022-08-17 07:14 UTC, AYakhimovich commented on services/weatherService.js
> +}
add new line and put descriptions into the constants.js:

```
wheatherDescriptionEnum = {
  CLOUDS: 'Clouds',
  RAIN: 'Rain'
  CLEAR: 'Clear'
}

```

2022-08-17 07:14 UTC, AYakhimovich commented on services/weatherService.js
> +	}
put selectors into the constants:


```
const WHEATHER_SELECTOR = .'weather__select';
const INFO_COUNTRY_SELECTOR = '.weather__info-country';

```

2022-08-17 07:14 UTC, AYakhimovich commented on styles.scss
> +}
add new line

2022-08-17 07:14 UTC, AYakhimovich commented on css/styles.css
> +body {
please use scss and put the colors and some of the main sizes into the constants

2022-08-17 07:14 UTC, AYakhimovich commented on index.js
> +  weatherService.showDescription(data.weather[0].main);
you can create one method in weatherService and call it show, to show all of this data, btw, weatherService can just receive instance of WeatherResource() and data could be received inside weatherService

2022-08-17 07:15 UTC, AYakhimovich commented
@vlad133L cool, good job!

need to add some changes to make the code more beautiful

2022-12-20 00:41 UTC, ai-yakhimovich requested changes

2022-12-20 00:41 UTC, ai-yakhimovich commented on server.js
> +      res.status(400).json({ message: 'Bad request' });
в данном случае должны быть ошибка 500 - это значит серверная ошибка, ошибки >= 400 имеют несколько другую смысловую нагрузку

2022-12-20 00:41 UTC, ai-yakhimovich commented on server.js
> +        `https://fcc-weather-api.glitch.me/api/current?lat=${query.lat}&lon=${query.lon}`,
лучше положить в constants url и создать метод, который будет строить урл

2022-12-20 00:41 UTC, ai-yakhimovich commented on server.js
> +const PORT = process.env.PORT || 5000;
дефолтное значение тоже желательно в константы вынесте

2022-12-20 00:41 UTC, ai-yakhimovich commented on server.js
> +      const data = await fetch(
создай метод getData и в него положи fetch + распаковку  response, этот метод лучше положить в отдельный класс, например, requestService

2022-12-20 00:41 UTC, ai-yakhimovich commented on server.js
> +  };
положи хедеры в константы

2022-12-20 00:41 UTC, ai-yakhimovich commented on server.js
> +  if (req.method === 'GET') {
создай метод handleRequest и в нем пусть будет это if

2022-12-20 00:41 UTC, ai-yakhimovich commented on services/weatherResource.js
> +    this.baseUrl = baseUrl;
baseUrl будет всегда одинаков, поэтому его лучше из констант брать, а не прокидывать

2022-12-20 00:41 UTC, ai-yakhimovich commented on services/weatherResource.js
> +      const data = await response.json();
здесь можно использовать тот же метод getData

2022-12-20 00:41 UTC, ai-yakhimovich commented on services/weatherResource.js
> +        country: data.sys.country,
создай wheatherMapper и там делай этот маппинг

2022-12-20 00:41 UTC, ai-yakhimovich commented on index.js
> +  weatherService.showDescription(data.description);
создай один метод в weatherService

2022-12-20 00:41 UTC, ai-yakhimovich commented on css/styles.css
> +  background-color: #a5aac1;
цвета положи в константы

2023-02-16 23:20 UTC, merged